# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Library of Digital Latin Texts
email: info@digitallatin.org
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ldlt.digitallatin.org/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: digitallatin
github_username:  Library-of-Digital-Latin-Texts

# Build settings
theme: minima #consider: jekyll-theme-cayman
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
# Where things are
source              : .
destination         : ./docs
collections:
  editions:
    output: true
# plugins_dir         : _plugins # takes an array of strings and loads plugins in that order
layouts_dir         : _layouts
# data_dir            : _data
includes_dir        : _includes
sass:
  sass_dir: assets/css
include             : [".htaccess"]
exclude             : ["Gemfile", "Gemfile.lock", "node_modules", "sources", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/", "xslt"]
keep_files          : [".git", ".svn"]
encoding            : "UTF-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : false

# Filtering Content
show_drafts         : false
limit_posts         : 0
future              : false
unpublished         : false

# Plugins
whitelist           : []

# Conversion
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false

# Serving
detach              : false
port                : 4000
host                : 127.0.0.1
show_dir_listing    : false

# Outputting
permalink           : date
paginate_path       : /page:num


quiet               : false
verbose             : false
defaults            : []

liquid:
  error_mode        : warn
  strict_filters    : false
  strict_variables  : false